include ./colors.conf

font_family family="FiraCode Nerd Font" features="cv14 cv30 ss09 cv25 cv26 cv28 cv32 ss07 ss10"
font_size 12
italic_font      family="Fira Mono"
bold_italic_font family="Fira Mono" style="Bold Italic"

#background_opacity 0.7

enable_audio_bell false

remember_window_size  false
initial_window_width  640
initial_window_height 400

window_padding_width 5
cursor_shape beam
confirm_os_window_close -1

